# Generated by Django 6.0.1 on 2026-01-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='bezel',
            field=models.CharField(blank=True, help_text='e.g. Fluted', max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='case_material',
            field=models.CharField(blank=True, help_text='e.g. Oystersteel', max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='collection_type',
            field=models.CharField(choices=[('CLASSIC', 'Classic Watches'), ('PROFESSIONAL', 'Professional Watches')], default='CLASSIC', max_length=20),
        ),
        migrations.AddField(
            model_name='watch',
            name='diameter',
            field=models.CharField(blank=True, help_text='e.g. 41 mm', max_length=50),
        ),
        migrations.AddField(
            model_name='watch',
            name='movement',
            field=models.CharField(blank=True, help_text='e.g. Perpetual, mechanical, self-winding', max_length=100),
        ),
    ]
